#' Generate request for the [MediaWiki Action
#' API](https://www.mediawiki.org/wiki/API:Main_page)
#'
#' @param ... Parameters for the request
#' @param action The action to perform, typically 'query'
#' @param language The language edition of Wikipedia to request, e.g. 'en' or
#'   'fr'
#'
#' @return An HTTP response: an S3 list with class httr2_request.
#' @export
#'
#' @examples
#' # List the first 10 pages in the category 'Australian historians'
#'
#' request <- wiki_action_request(
#'   list = "categorymembers",
#'   cmtitle = "Category:Australian_historians",
#'   cmlimit = 10
#' )
#' request %>%
#'   httr2::req_perform() %>%
#'   httr2::resp_body_json() %>%
#'   .$query %>%
#'   .$categorymembers
#'
wiki_action_request <- function(..., action = "query", language = "en") {
  base_url <- glue::glue("https://{language}.wikipedia.org/w/api.php")
  params <- rlang::list2(
    action = action,
    format = "json",
    formatversion = "2",
    ...
  )
  req <- httr2::request(base_url) %>%
    httr2::req_url_query(!!!params) %>%
    httr2::req_user_agent(
      "wikkitidy R package (https://github.com/wikihistories/wikkitidy)"
    )
}

#' Specify which pages to list from the action API
#'
#' See [API:Lists](https://www.mediawiki.org/wiki/API:Lists) for available
#' list actions. Each list action returns a list of pages, typically including
#' their pageid, [namespace](https://www.mediawiki.org/wiki/Manual:Namespace)
#' and title. Individual lists have particular properties that can be requested,
#' which are usually prefaced with a two-word code based on the name of the
#' list (e.g. specific properties for the `categorymembers` list action are
#' prefixed with `cm`).
#'
#' When the request is performed, the data is returned in the body of the
#' request under the `query` object, labeled by the chosen list action.
#'
#' If you want to study the actual pages listed, it is adviseable to retrieve
#' the pages directly using a generator, rather than listing their IDs using a
#' list action. When using a list action, a second request is required to get
#' further information about each page. Using a generator, you can query pages
#' and retrieve their relevant properties in a single API call.
#'
#' @param .req A httr2_request, e.g. generated by `wiki_action_request`
#' @param list The [type of list](https://www.mediawiki.org/wiki/API:Lists) to return
#' @param ... Additional parameters to the query, e.g. to set configure list
#'
#' @return An HTTP response: an S3 list with class httr2_request
#' @export
#'
#' @examples
#' # Get the ten most recently added pages in Category:Physics
#'
#' resp <- wiki_action_request() %>%
#'   query_list_of("categorymembers", cmsort = "timestamp",
#'     cmdir = "desc", cmtitle = "Category:Physics") %>%
#'   httr2::req_perform() %>%
#'   httr2::resp_body_json()
#'
#' resp$query$categorymembers
query_list_of <- function(.req, list, ...) {
  .set_action(.req, "list", list, ...)
}

#' Specify which pages to generate from the Action API
#'
#' See [API:Lists](https://www.mediawiki.org/wiki/API:Lists) for available
#' generators. Most list actions in the MediaWiki API can also be used as
#' generators. If you use a list action as a generator, then you will receive
#' the data in the `pages` attribute of the response body, rather than under
#' the name of the generator. You can `query_generate_pages` with
#' `query_page_properties` to choose what properties of each page to return.
#'
#' To set additional parameters to a generator, prepend the parameter with "g".
#' For instance, to set a limit of 10 to the number of pages returned by the
#' `categorymembers` generator, set the parameter `gcmlimit = 10`.
#'
#' @param .req A httr2_request, e.g. generated by `wiki_action_request`
#' @param generator The [type of generator](https://www.mediawiki.org/wiki/API:Lists) to return
#' @param ... Additional parameters to the generator
#'
#' @return An HTTP response: an S3 list with class httr2_request
#' @export
#'
#' @examples
#' # Search for articles about seagulls
#'
#' resp <- wiki_action_request() %>%
#'   query_generate_pages("search", gsrsearch="seagull") %>%
#'   httr2::req_perform() %>%
#'   httr2::resp_body_json()
#'
#' resp$query$pages
query_generate_pages <- function(.req, generator, ...) {
  .set_action(.req, "generator", generator, ...)
}

#' Choose properties to return for pages from the action API
#'
#' See [API:Properties](https://www.mediawiki.org/wiki/API:Properties) for a list of available properties. Many have
#' additional parameters to control their behavior, which can be passed
#' to this function as named arguments.
#'
#' `query_page_properties` can be used in combination with `query_generate_pages`
#' to choose what information to retrieve about the generated pages. If you
#' already have a list of page ids or titles, you can build a query using
#' `query_page_properties` to collect information about them.
#'
#' @param .req A httr2_request, e.g. generated by `wiki_action_request`
#' @param properties The properties to request, as either a character vector
#'   or a string with properties separated by "|"
#' @param ... Additional parameters to pass, e.g. to modify what is returned
#'   by the property request
#'
#' @return An HTTP response: an S3 list with class httr2_request
#' @export
#'
#' @examples
#' # Search for articles about seagulls and return their links to other
#' # language wikis
#'
#' resp <- wiki_action_request() %>%
#'   query_generate_pages("search", gsrsearch="seagull") %>%
#'   query_page_properties("langlinks") %>%
#'   httr2::req_perform() %>%
#'   httr2::resp_body_json()
#'
#' resp$query$pages
query_page_properties <- function(.req, properties, ...) {
  .set_action(.req, "prop", properties, ...)
}

.set_action <- function(.req, action_type, action, ...) {
  action_type <- rlang::ensym(action_type)
  action_string <- paste0(action, collapse = "|")
  action_params <- rlang::list2(...)
  httr2::req_url_query(.req = .req, !!action_type := action_string, !!!action_params)
}
